name: glass_bottom_nav_bar
description: A beautiful and customizable glassmorphism bottom navigation bar for Flutter applications.
version: 0.0.1
repository: https://github.com/your_username/glass_bottom_nav_bar
issue_tracker: https://github.com/your_username/glass_bottom_nav_bar/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
